# Generated by Django 5.2 on 2025-05-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_symptom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.medicalspecialty')),
            ],
        ),
    ]
