# Generated by Django 5.2 on 2025-05-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('services', '0003_symptom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='specialty',
        ),
        migrations.AddField(
            model_name='clinic',
            name='specialties',
            field=models.ManyToManyField(related_name='clinics', to='services.medicalspecialty'),
        ),
    ]
