# Generated by Django 5.2 on 2025-05-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_remove_clinic_specialty_clinic_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.CharField(default='Sibiu', max_length=100),
            preserve_default=False,
        ),
    ]
