# Generated by Django 5.2 on 2025-05-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_alter_clinic_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
