# Generated by Django 5.2 on 2025-04-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalspecialty',
            options={'verbose_name_plural': 'Medical Specialties'},
        ),
        migrations.AlterField(
            model_name='medicalspecialty',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
