# Generated by Django 5.2 on 2025-05-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_medicalspecialty_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='services.medicalspecialty')),
            ],
            options={
                'verbose_name_plural': 'Symptoms',
            },
        ),
    ]
