# Generated by Django 5.2 on 2025-05-13 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('services', '0003_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.medicalspecialty'),
        ),
    ]
