# Generated by Django 5.2 on 2025-05-15 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_specialty'),
        ('clinics', '0005_clinic_email_clinic_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.clinic'),
        ),
    ]
